# sysusers.d template. Review fixed IDs for conflicts BEFORE installation.
g eye-for-an-eye-ipc 10000
u eye-for-an-eye 10001:10000 "Eye for an Eye analysis" /var/lib/eye-for-an-eye /usr/sbin/nologin
u eye-for-an-eye-capture 10002:10000 "Eye for an Eye capture" /nonexistent /usr/sbin/nologin
